urls.py
from django.contrib.auth.views import login, logout
from django.conf.urls.defaults import *
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Test.views import chapters, task, end, add_answer, students, test_detail, tests, tests_to_pdf, test_chart, theory_reader, bio, feedback, info, inquisitive, method

admin.autodiscover()
urlpatterns = patterns('',
    (r'^accounts/login/$', login),
    (r'^accounts/logout/$', logout),
    (r'^accounts/profile/$', chapters),
    (r'^chapter/$', chapters),
    (r'^chapter/([\d]*)/$', chapters),
    (r'^chapter/([\d]*)/final/$', chapters, {'final' : True}),
    (r'^chapter/([\d]*)/train/$', chapters, {'final' : False}),
    (r'^chapter/([\d]*)/task/0/$', end),
    (r'^chapter/[\d]*/task/([\d]*)/$', task),
    (r'^chapter/[\d]*/task/([\d]*)/answer/$', add_answer),
    (r'^theory/[\w]*.html$', theory_reader),
    (r'^statistics/students/$', students),
    (r'^statistics/tests/$', tests),
    (r'^statistics/tests/pdf/$', tests_to_pdf, {'chapter_id' : 1}),
    (r'^statistics/test/([\d]*)/$', test_detail),
    (r'^statistics/chart/chapter/([\d]*)/student/([\d]*)/$', test_chart),
    (r'^bio/$', bio),
    (r'^method/$', method),
    (r'^inquisitive/$', inquisitive),
    (r'^info/([\d]*)/$', info),
    (r'^info/parents/([\d]*)/$', info, {'for_parents' : True}),
    (r'^feedback/$', feedback),
    # Example:
    # (r'^TestTask/', include('TestTask.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^$', chapters),
)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += patterns('',
    url(r'^captcha/', include('captcha.urls')),
)

Test/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Student (models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    className = models.CharField(max_length=10)
    def __unicode__(self):
        return self.lastName + " " + self.firstName
    class Meta:
        ordering = ['className', 'lastName', 'firstName']

class Chapter (models.Model):
    shortName = models.CharField(max_length=30)
    description = models.CharField(max_length=100)
    active = models.BooleanField(default=False)
    timeLimit = models.IntegerField(default=0)
    easy = models.IntegerField(blank=True)
    medium = models.IntegerField(blank=True)
    hard = models.IntegerField(blank=True)
    grade = models.IntegerField(blank=True)
    def __unicode__(self):
        return self.shortName
    class Meta:
        ordering = ['shortName']

class Task (models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=600)
    position = models.IntegerField()
    chapter = models.ForeignKey(Chapter)
    complexity = models.IntegerField()
    theoryLink = models.CharField(blank=True, max_length=400)
    def __unicode__(self):
        return  self.title
    class Meta:
        ordering = ['chapter', 'position']

class Option (models.Model):
    text = models.CharField(max_length=80)
    value = models.CharField(max_length=30, blank=True)
    position = models.IntegerField()
    correct = models.BooleanField()
    task = models.ForeignKey(Task)
    def __unicode__(self):
        return self.text
    class Meta:
        ordering = ['task', 'position']

class TestSession (models.Model):
    testDate = models.DateField()
    duration = models.IntegerField(blank=True)
    student = models.ForeignKey(User)
    correct = models.IntegerField(blank=True)
    total = models.IntegerField(blank=True)
    final = models.BooleanField()

class TestSequence (models.Model):
    task = models.ForeignKey(Task)
    position = models.IntegerField()
    test_session = models.ForeignKey(TestSession)

class Answer (models.Model):
    testSession = models.ForeignKey(TestSession)
    selected = models.ManyToManyField(Option)
    value = models.CharField(max_length=30, blank=True)
    position = models.IntegerField()
    class Meta:
        ordering = ['position']

class Feedback (models.Model):
    email = models.EmailField(blank=False)
    message = models.CharField(blank=False, max_length=500)
    post_date = models.DateTimeField(blank=False)
    def __unicode__(self):
        return self.post_date.strftime('%d %b %Y') + ' ' + self.email + ' ' + self.message
    class Meta:
        ordering = ['post_date']

Test/forms.py
# coding=UTF-8
from django import forms
from captcha.fields import CaptchaField

__author__ = 'Frostbite'
class SearchTest(forms.Form):
    name = forms.CharField(max_length = 100, required=False, label="",
                           widget=forms.widgets.TextInput(attrs={'placeholder': u'Учащийся'}))
    em = {"required": u"Введите дату", "invalid": u"Неправильный формат даты"}
    start = forms.DateField(widget=forms.widgets.DateInput(format="%d.%m.%Y", attrs={'placeholder': u'От (дд.мм.гггг)'}),
                            required=False, label="", input_formats = ["%d.%m.%Y"], error_messages = em)

    end = forms.DateField(widget=forms.widgets.DateInput(format="%d.%m.%Y", attrs={'placeholder': u'До (дд.мм.гггг)'}),
                          required=False, label="", input_formats= ["%d.%m.%Y"], error_messages= em)
    page = forms.IntegerField(required=False, widget=forms.widgets.HiddenInput())

    pagesize = forms.ChoiceField(widget=forms.Select(attrs = {'class' : "input-mini"}),
        choices=(('10', '10'),('25', '25'),('50', '50'), (u'Все', u'Все')),
        initial="10", required=False)

    def clean(self):
        cleaned_data = self.cleaned_data
        s = cleaned_data.get("start")
        e = cleaned_data.get("end")

        if s and e and s > e:
            raise forms.ValidationError(u"Начальная дата не должна быть позже  конечной.")
        # Always return the full collection of cleaned data.
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(SearchTest, self).__init__(*args, **kwargs)
        self.right_wing = 0#make in useless unless deliberately set
        self.left_wing = 10000
        self.middle = 0

    def update_pagesize_class(self, cls):
        self.fields['pagesize'].widget.attrs['class'] = 'input-mini ' + cls

class FeedbackForm(forms.Form):
    email = forms.EmailField(required=True, label=u'Электропочта',
                             error_messages={"required": u"Введите адрес", "invalid": u"Неправильный формат адреса"},
                             max_length=150,widget=forms.TextInput(attrs={'class' : 'field span6'}))
    message = forms.CharField(required=True, label=u'Сообщение',
                              error_messages={"required": u"Введите сообщение"},
                              widget=forms.Textarea(attrs={'rows': 10, 'cols': 85, 'class' : 'field span6'}))
    captcha = CaptchaField(required=True, label=u'Решите пример',
                           error_messages={"required": u"Решите пример правильно", "invalid": u"Неправильный ответ"})

Test/views.py
# Create your views here.
# coding=UTF-8
from cStringIO import StringIO
from datetime import datetime
#import logging
from itertools import chain
import random
import time
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models.query_utils import Q
from django.http import HttpResponse
from django.shortcuts import render_to_response, redirect
from django.template.context import RequestContext
import reportlab
from reportlab.pdfbase.pdfmetrics import registerFont
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas
from forms import SearchTest, FeedbackForm

from models import Chapter, Task, Option, TestSession, TestSequence, Feedback
import settings
#l = logging.getLogger('django.db.backends')
#l.setLevel(logging.DEBUG)
#l.addHandler(logging.StreamHandler())
class Summary:
    def __init__(self, taskText, correctText, actualText, link = None):
        self.task = taskText
        self.correct = correctText
        self.actual = actualText
        self.link = link

class Paginator_2(Paginator):
    def __init__(self, object_list, per_page, current_page, wing=2):
        super(Paginator_2, self).__init__(object_list, per_page)
        self.number = current_page
        self.wing = wing
    def _get_visible_page_range(self):
        if self.number == 0:
            return self.page_range
        end = self.num_pages + 1
        rng = [1]
        left = max(self.number - self.wing, 2)
        right = min(self.number + self.wing + 1, end)
        if left - 2 >= 1:
            rng.append(-1)
        rng.extend(range(left, right))
        if end - right >= 1:
            rng.append(-1)
        rng.append(end)
        return rng

    visible_page_range = property(_get_visible_page_range)

def get_params(request, additional= None, p_grade = None):
    chapter_list = Chapter.objects.filter(active=True)
    if p_grade is not None:
        chapter_list = chapter_list.filter(grade=p_grade)
    params = {'teacher': (bool(request.user.groups.filter(name='teacher'))),
              'chapter_list': chapter_list}
    if additional:
        params.update(additional)
    return params
def chapter_id_for_test_session(test_session):
    try:
        return test_session.answer_set.all()[0].selected.all()[0].task.chapter_id
    except Exception:
        return -1

#@login_required
def chapters(request, chapter_id=None, final = None):
    if chapter_id and not (final is None):
        try:
            del request.session['test']
        except KeyError:
            pass
        if final:
            request.session['final'] = final
            try:
                return test_detail(request,
                    TestSession.objects.filter(student=request.user, final=True,
                        answer__selected__task__chapter=chapter_id).distinct()[0].id)
            except IndexError:
                pass
            except TestSession.DoesNotExist:
                pass
        else:
            try:
                del request.session['final']
            except KeyError:
                pass
        testSession = TestSession()
        testSession.testDate = datetime.now()
        testSession.duration = 0
        testSession.student = request.user
        testSession.final = request.session.get('final', False)
        #generate random list of tasks
        chapter = Chapter.objects.get(id = chapter_id)
        easy = Task.objects.filter(chapter = chapter_id, complexity = 1).order_by('?')[:chapter.easy]
        medium = Task.objects.filter(chapter = chapter_id, complexity = 2).order_by('?')[:chapter.medium]
        hard = Task.objects.filter(chapter = chapter_id, complexity = 3).order_by('?')[:chapter.hard]
        tasks = list(chain(easy, medium, hard))
        testSession.total = len(tasks)
        testSession.save()
        request.session['test'] = testSession
        random.shuffle(tasks)
        k = 0
        for t in tasks:
            elem = TestSequence()
            elem.position = k
            elem.task = t
            elem.test_session = testSession
            elem.save()
            k += 1
        return task(request, 1)
    else:
        params = get_params(request)
        if chapter_id:
            params['chapter'] = Chapter.objects.get(id = chapter_id)
        return render_to_response("chapter.html", params, context_instance=RequestContext(request))
@login_required
def task(request, task_num):
    task_num  = int(task_num)
    isTeacher =  bool(request.user.groups.filter(name='teacher'))
    if isTeacher:
        return redirect("/chapter/")
    testSession = request.session.get('test')
    if testSession is None:
        return redirect("/chapter/")
    testSession.duration = (datetime.now() - testSession.testDate).seconds
    testSession.save()
    test_sequence = TestSequence.objects.filter(test_session = testSession).order_by('position')
    task_list = []
    type = 0
    for ts in test_sequence:
        task_list.append(ts.task)
    task = test_sequence[task_num - 1].task
    options = task.option_set.all()
    for opt in options:
        if opt.correct:
            type += 1
        if opt.value:
            type = -1

    return render_to_response("task.html", {'task': task,
                                            'type': type,
                                            'list' : task_list,
                                            'next' : task_num + 1,
                                            'tictac' : testSession.duration,
                                            'limit' : task.chapter.timeLimit,
                                            'chapter_list' : Chapter.objects.filter(active = True)},
                              context_instance=RequestContext(request))
@login_required
def add_answer(request, task_num):
    task_num = int(task_num)
    try:
        if request.method == 'POST':
            try:
                testSession = request.session['test']
            except KeyError :
                testSession = None
            tsStep = TestSequence.objects.filter(test_session = testSession, position = task_num - 2)[0]#current task
            if request.POST.has_key('giveup'):
                return redirect('/chapter/{0:d}/task/0/'.format(tsStep.task.chapter_id), context_instance=RequestContext(request))
            chosen = request.POST.getlist('option')
            answers = testSession.answer_set.all()
            answer  = None
            for ans in answers:
                if ans.selected.all()[0].task == tsStep.task:
                    answer = ans
                    break
            if answer is None:
                answer = testSession.answer_set.create()
            else:
                answer.selected.clear()
            for optId in chosen:
                try:
                    opt = Option.objects.get(id = int(optId))
                    if opt.task != tsStep.task or (opt.task == tsStep.task and opt.value != '' and opt.value is not None):#a chance that entered value is ID of another option
                        raise ValueError
                    if opt.value is not None:
                        answer.selected.add(opt)#value from form is not ID but entered data
                except (Option.DoesNotExist, ValueError):
                    answer.value = optId
                    answer.selected.add(tsStep.task.option_set.all()[0])
            answer.position = task_num
            answer.save()
            c = check_answer(answer, [])
            if testSession.correct is None:
                testSession.correct = 0
            if c[0]:
                testSession.correct += 1
            testSession.save()
            request.session['test'] = testSession
            if TestSequence.objects.filter(test_session = testSession).count() < task_num:
                task_num = 0
            return redirect('/chapter/{0:d}/task/{1:d}/'.format(tsStep.task.chapter_id, task_num), context_instance=RequestContext(request))
        else:
            return redirect("/chapter/")
    except Task.DoesNotExist:
        return redirect("/chapter/")

def set_test_session_data(chapter, test_session):
    summary, test_session.correct = get_test_session_summary(test_session, chapter)
    test_session.save()
    return summary


def check_answer(a, answered_task_ids):
    opts = a.selected.all()
    correctTexts = []
    actualTexts = []
    task = None
    correct = 0
    if len(opts) > 0:
        task = opts[0].task
        answered_task_ids.append(task.id)
        taskOpts = task.option_set.filter(correct=True)
        for opt in taskOpts:
            if opt.value is None or opt.value == '':
                correctTexts.append(opt.text)
            else:
                correctTexts.append(opt.value)
        if a.value is not None and opts[0].value.replace(" ", "") != a.value.replace(" ", ""):
            actualTexts.append(a.value)
        elif opts.count() == 1 and not opts[0].correct:
            actualTexts.append(opts[0].text)
        elif len(correctTexts) > 1 and set(opts).intersection(taskOpts) != set(taskOpts):
            for o in opts:
                actualTexts.append(o.text)
        else:
            correct = 1
    return correct, actualTexts, correctTexts, task


def get_test_session_summary(test_session, chapter = None):
    answers = test_session.answer_set.all()
    correct = 0
    aggregate = []
    answered_task_ids = []
    for a in answers:
        c, actualTexts, correctTexts, task = check_answer(a, answered_task_ids)
        correct += c
        if task:
            aggregate.append(Summary(taskText=task.description,
                correctText=correctTexts, actualText=actualTexts, link = task.theoryLink))
            chapter = task.chapter
    if (chapter.easy if chapter.easy else 0) + (chapter.medium  if chapter.medium else 0)+ \

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="description" content="Сайт учителя математики Морозовой Ирины Сергеевны">
    <script type="text/javascript" src="/static/scripts/jquery.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.js"></script>
    <link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
{#        <link href="/static/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">#}

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script type="text/javascript">
    var selectedPage = '';
</script>
    <link type="text/css"  href="/static/css/base.css" rel="stylesheet"/>
    {% block links %}{% endblock %}
    <title>{% block title %}Тестирование{% endblock %}</title>
</head>
<body onload="{% block loader %}{% endblock %}">
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            {% block header %}
                <div class="nav">
                    <ul class="nav">
                        <li id="mainpage"><a href="/chapter/">Главная</a></li>
                        {% if chapter_list %}
                            {% if teacher %}
                                <li class="dropdown" id="testpage">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Статистика <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        {%  block menuinfo %}
                                            <li><a href="/statistics/students/">Статистика по студентам</a></li>
                                            <li><a href="/statistics/tests/">Статистика по тестам</a></li>
                                        {% endblock %}
                                    </ul>
                                </li>
                            {% endif %}
                        {% endif %}
                        <li class="dropdown" id="studentpage">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Ученикам <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/inquisitive/">Любознательным</a></li>
                                <li class="divider"/>
                                <li><a href="/info/5/">5 класс</a></li>
                                <li><a href="/info/7/">7 класс</a></li>
                            </ul>
                        </li>
                        <li id="parentpage"><a href="/info/parents/5/">Родителям</a></li>
                        <li id="methodpage"><a href="/method/">Методичка</a></li>
                        <li class="dropdown" id="aboutpage">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Обо мне <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/bio/">Биография</a></li>
                                <li><a href="/feedback/">Обратная связь</a></li>
                            </ul>
                        </li>
                        <li class="pull-right"><a href="http://new.mcko.ru/">Электронный Журнал</a></li>
                        <li><form class="navbar-form pull-right">
                            {% if user.is_authenticated %}<a class="btn btn-success" href="/accounts/logout/">Выход</a>{% else %}<a class="btn btn-success" href="/accounts/login/">Войти</a>{% endif %}
                        </form></li>
                    </ul>
                </div><!--/.nav-collapse -->
            {% endblock %}
        </div>
    </div>
</div>
<div class="container" id="main-container">
    <!-- Main hero unit for a primary marketing message or call to action -->
    <div class="hero-unit">
        <H1 id="main">Сайт учителя математики<br>Морозовой Ирины Сергеевны</H1>
    </div>
    {% if user.is_authenticated %}
        <div class="row">
            <div class="span8">&nbsp;</div>
            <div class="span3">

                <span class="pull-right label label-info" id="user_label">Пользователь: {{ user.first_name }} {{ user.last_name }}</span>

            </div>
            <div class="span1">&nbsp;</div>
        </div>
    {% endif %}
    {% block main %}{% endblock %}
    {% block footer %}
        <footer>
            <!-- Поместите этот тег туда, где должна отображаться кнопка +1. -->
            <div class="g-plusone" data-annotation="inline"></div>

            <!-- Поместите этот вызов функции отображения в соответствующее место. -->
            <script type="text/javascript">
                window.___gcfg = {lang: 'ru'};

                (function() {
                    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                    po.src = 'https://apis.google.com/js/plusone.js';
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                })();
            </script><br/><span class="copyright">© 2011, Морозова Ирина, Морозов Максим, frostbite3-at-gmail.com</span>
            {% if work_time != None %}
                <div>
                {% for tm in work_time %}
                    time = {{ tm }};&nbsp;
                {% endfor %}
                </div>
            {% endif %}
        </footer>
    {% endblock %}
</div>
<!-- Yandex.Metrika counter -->
<div style="display:none;"><script type="text/javascript">
    (function(w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter13027249 = new Ya.Metrika({id:13027249, enableAll: true});
            }
            catch(e) { }
        });
    })(window, "yandex_metrika_callbacks");
</script></div>
<script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript" defer="defer"></script>
<noscript><div><img src="//mc.yandex.ru/watch/13027249" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<script type="text/javascript" language="JavaScript">
    var $buoop = {vs:{i:8,f:12,o:11,s:5,n:9}}
    $buoop.ol = window.onload;
    $(document).ready(function(){
        $('#' + selectedPage).addClass('active');
        try {if ($buoop.ol) $buoop.ol();}catch (e) {}
        var e = document.createElement("script");
        e.setAttribute("type", "text/javascript");
        e.setAttribute("src", "http://browser-update.org/update.js");
        document.body.appendChild(e);
    });
</script>
</body>
</html>

templates/bio.html
{% extends "base.html" %}
{% block main %}
    <div class="row">
        <div class="span1">&nbsp;</div>
        <div class="span10">
            <H2>Морозова Ирина Сергеевна</H2>
                <div>&nbsp;</div>
                <h3>Образование: </h3><img src="/static/images/mis.jpg" alt="" style="margin-left: 10px; float: right;">
                <p>Московский Педагогический Университет, диплом с отличием. Квалификация: Учитель математики и информатики</p>
                <h3>Награды:</h3>
                <ul>
                    <li>
                        Финалист конкурса "Учитель года", 2003 Щелковского района Московской области
                    </li>
                    <li>
                        Победитель всероссийского конкурса учителей математики и физики фонда Дмитирия Зимина "Династия", 2006
                    </li>
                </ul>
                <h3>Моя педагогическая философия:</h3>
                <p>Есть притча о царе, который  мечтал осчастливить свой народ и обратился за советом к мудрецам. Те задали ему три вопроса: какой час на земле самый главный, какой человек на земле самый главный,  какое дело на земле самое главное? Царь не сумел найти ответы на эти вопросы. А они были очень просты: самый главный час –  настоящий, тот,  который сейчас наступил; самым главным человеком является тот, что сейчас с тобой; дело, которое ты сейчас делаешь, и является самым важным. Применительно к моей педагогической философии и моему учительскому счастью отвечу на эти вопросы так. Любой урок – самый главный, ибо завтра будут уже другие уроки. Давать их ученикам – вот мое первое педагогическое счастье. Главный человек для меня –  мой ученик. Важно найти для каждого именно то слово, в котором он сейчас нуждается. В этом заключается мое второе счастье учителя. Именно сейчас я могу зажигать свет в их сердцах, звать к добру, задавать цель видеть смысл в любом деле. Вот мое третье счастье.</p>
                <div style="text-align: center; display: none;"><img id="sln" src="/static/images/good.jpg" alt=""></div>
                <script type="text/javascript">
                    $(function() {
                        $("#sln")
                                .mouseover(function() {
                                    var src = "/static/images/evil.jpg";
                                    $(this).attr("src", src);
                                })
                                .mouseout(function() {
                                    var src = "/static/images/good.jpg";
                                    $(this).attr("src", src);
                                });
                    });
                </script>
        </div>
        <div class="span1">&nbsp;</div>
    </div>
    <script type="text/javascript" language="JavaScript">
        $(document).ready(function(){
            selectedPage = 'aboutpage';
        });
    </script>
{% endblock %}

templates/charts.html
<html>
<head>
    <link type="text/css"  href="/static/css/base.css" rel="stylesheet"/>
    <script type="text/javascript" src="/static/scripts/jquery.min.js"></script>
    <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="/static/scripts/excanvas.min.js"></script><![endif]-->
    <script language="javascript" type="text/javascript" src="/static/scripts/jquery.flot.js"></script>
</head>
<body style="height: 30px">
<h2>Учащийся: {{ student.first_name }}&nbsp;{{ student.last_name }}, Раздел: {{ chapter.shortName }}</h2>
<div>&nbsp;</div>
{#    <img src="/statistics/chart/chapter/{{ 1 }}/student/{{ student.id }}/draw/"/>#}
<div id="placeholder" style="width:720px;height:300px;margin-left: 16px;"></div>
<script type="text/javascript">
    $(function () {
        var data = [{% for bar in stats %}['{{ forloop.counter0 }}', {{ bar.1 }}]{% if not forloop.last %},{% endif %}{% endfor %}];
        $.plot($("#placeholder"), [
            { data: data, lines: { show: true }, points:{ show: true }}
        ], {
            xaxis: {
                ticks: [{% for bar in stats %}[{{ forloop.counter0 }},{% if forloop.counter0|divisibleby:sparserate %}"{{ bar.0|date:"j.m.Y" }}"{% else %}""{% endif %}]{% if not forloop.last %},{% endif %}{% endfor %}]
            },
            yaxis: {
                ticks: {{ max }},
                min: 0,
                max: {{ max }}
            },
            grid: {
                backgroundColor: { colors: ["#fff", "#eee"] }
            }
        });
    });
</script>
</body>
</html>

templates/searchform.html
<div id="searchform">
    <form method="GET" class="form-inline">
        <div class="form-row">
            {% if form.non_field_errors %}
                <div>
                    {% for err in form.non_field_errors %}
                        <div class="alert">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            {{ err }}</div>
                    {% endfor %}
                </div>
            {% endif %}
            {% for field in form.visible_fields %}
                {% for err in field.errors %}
                    <div class="alert">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        {{ err }}</div>
                {% endfor %}
            {% endfor %}
            {% for field in form.visible_fields %}
                {% if field.name != form.pagesize.name %}
                    {{ field }}
                {% endif %}
            {% endfor %}
            <a class="btn btn-success" id="submit">Найти</a>
            {{ form.page }}
        </div>
        <div class="form-row">
            <div class="pagination">
                <ul>
                    {% if stats.paginator and stats.paginator.num_pages > 1 %}
                        {% if stats.has_previous %}
                            <li><a id="prev" href="#"><<</a></li>
                        {% endif %}
                        {% for pn in stats.paginator.visible_page_range %}
                            {% if pn > 0 %}
                                <li class="{% if pn == stats.number %}active{% endif %}"><a href="#" class="pagelink">{{ pn }}</a>
                                </li>
                            {% else %}
                                <li><a href="#">...</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if stats.has_next %}
                            <li><a id="next" href="#">>></a></li>
                        {% endif %}
                    {% endif %}
                    <li> {{ form.pagesize }}</li>
                </ul>
            </div>
        </div>
    </form>

</div>
<script>
    $(function () {
        $.fn.datepicker.defaults = {
            format:'dd.mm.yyyy', language:'ru'
        };
        //$.datepicker.setDefaults( $.datepicker.regional[ "ru" ]);
        $("#id_start").datepicker();
        $("#id_end").datepicker();
        $('input').placeholder();
    });

    $('#next').click(
            function () {
                var val = $('#id_page').val();
                if (val == "")
                    val = 1;
                $('#id_page').val(parseInt(val) + 1);
                $('#searchform').find('> form').submit();
            }
    );
    $('#prev').click(
            function () {
                $('#id_page').val(parseInt($('#id_page').val()) - 1);
                $('#searchform').find('> form').submit();
            }
    );
    $('.pagelink').click(
            function (e) {
                $('#id_page').val(parseInt($(this).text()));
                $('#searchform').find('> form').submit();
            }
    );
    $('#submit').click(
            function (e) {
                $('#searchform').find('> form').submit();
            }
    )
</script>